In [1]:
import pandas as pd
import yaml

In [2]:
with open("../config.yaml", "r") as file:
    config = yaml.safe_load(file)

In [10]:
config

{'data': {'raw': {'file1': '../data/raw/df_final_demo.txt',
   'file2': '../data/raw/df_final_experiment_clients.txt',
   'file3': '../data/raw/df_final_web_data_pt_1.txt',
   'file4': '../data/raw/df_final_web_data_pt_2.txt'},
  'clean': {'file1': '../data/clean/file1.csv'}}}

In [5]:
df_d = pd.read_csv(config['data']['raw']['file1'], quotechar='"')
df_c = pd.read_csv(config['data']['raw']['file2'], quotechar='"')

In [6]:
def clean_demo(df):
    df2 = df.copy()
    df2.dropna(thresh=2)
    return df2

def find_age_tenure_mismatch(df):
    df2 = df.copy()
    df2 = df2[df2.clnt_age> df2.clnt_tenure_yr]
    return df2

def clean_clients_dropna(df):
    df2 = df.copy()
    df2.rename(str.lower, axis="columns")
    df2 = df2.dropna()
    return df2

def find_children(df):
    df2 = df.copy()
    df2 = df2[df2.clnt_age<18]
    return df2

In [7]:
df_d = clean_demo(df_d)
df_c = clean_clients_dropna(df_c)
df_c

       client_id Variation
0        9988021      Test
1        8320017      Test
2        4033851   Control
3        1982004      Test
4        9294070   Control
...          ...       ...
50495     393005   Control
50496    2908510   Control
50497    7230446      Test
50498    5230357      Test
50499    6334360      Test

[50500 rows x 2 columns]

In [14]:
df_control = df_c[df_c.Variation=='Control']
df_test = df_c[df_c.Variation=='Test']

       client_id Variation
2        4033851   Control
4        9294070   Control
7        6651403   Control
9        2105948   Control
12       9814849   Control
...          ...       ...
50491    4364429   Control
50493    8730282   Control
50494    5305116   Control
50495     393005   Control
50496    2908510   Control

[23532 rows x 2 columns]

In [15]:
df_d.to_csv("../data/clean/df_demo_cleaned.csv", index=False, encoding= "utf-8", sep = ",")
df_c.to_csv("../data/clean/df_experiment_clients_cleaned.csv", index=False, encoding= "utf-8", sep = ",")
df_control.to_csv("../data/clean/df_control_cids.csv", index=False, encoding= "utf-8", sep = ",")
df_test.to_csv("../data/clean/df_test_cids.csv", index=False, encoding= "utf-8", sep = ",")

In [52]:
#checked for null values
#df_d.isna().sum()

In [53]:
#inspected rows with nulls
#df_d[df_d.isna().any(axis=1)]

In [54]:
#trying to understand why so many children appear
#df_d[df_d.clnt_age<18]

In [55]:
#noticed many children had tenures longer than their lives
#df_d[df_d.clnt_age<df_d.clnt_tenure_yr]

In [56]:
#confirmed no errors in tenure month vs year
# df_d[df_d.clnt_tenure_mnth> (df_d.clnt_tenure_yr +1)*12]
 # df_d[df_d.clnt_tenure_mnth< (df_d.clnt_tenure_yr )*12]

In [57]:
#inspect values for errors
# df_d.describe()

In [58]:
#confirm no duplicates
#df_d.client_id.nunique(), df_d.client_id.count()

In [59]:
#look for empty values
#df_c.isna().sum()

In [60]:
# check if the proportion for test groups is approximately equal
#df_c.Variation.value_counts(normalize=True)

In [61]:
# looking at missing values
#df_c[df_c.isna().any(axis=1)]

In [62]:
#check if there are duplicates and what they are
#df_c.client_id.nunique(), df_c.client_id.count()