In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [3]:
df1 = pd.read_csv("https://raw.githubusercontent.com/bibianglez/project2_eda_inf_stats_tableau/refs/heads/main/data/raw/df_final_demo.txt")
df2 = pd.read_csv("https://raw.githubusercontent.com/bibianglez/project2_eda_inf_stats_tableau/refs/heads/main/data/raw/df_final_experiment_clients.txt")
df3 = pd.read_csv("https://raw.githubusercontent.com/bibianglez/project2_eda_inf_stats_tableau/refs/heads/main/data/raw/df_final_web_data_pt_1.txt")
df4 = pd.read_csv("https://raw.githubusercontent.com/bibianglez/project2_eda_inf_stats_tableau/refs/heads/main/data/raw/df_final_web_data_pt_2.txt")

In [4]:
display(df1.head())
display(df2.head())
display(df3.head())
display(df4.head())

,client_id,clnt_tenure_yr,clnt_tenure_mnth,clnt_age,gendr,num_accts,bal,calls_6_mnth,logons_6_mnth
0,836976,6.0,73.0,60.5,U,2.0,45105.30,6.0,9.0
1,2304905,7.0,94.0,58.0,U,2.0,110860.30,6.0,9.0
2,1439522,5.0,64.0,32.0,U,2.0,52467.79,6.0,9.0
3,1562045,16.0,198.0,49.0,M,2.0,67454.65,3.0,6.0
4,5126305,12.0,145.0,33.0,F,2.0,103671.75,0.0,3.0

   client_id Variation
0    9988021      Test
1    8320017      Test
2    4033851   Control
3    1982004      Test
4    9294070   Control

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04

,client_id,visitor_id,visit_id,process_step,date_time
0,763412,601952081_10457207388,397475557_40440946728_419634,confirm,2017-06-06 08:56:00
1,6019349,442094451_91531546617,154620534_35331068705_522317,confirm,2017-06-01 11:59:27
2,6019349,442094451_91531546617,154620534_35331068705_522317,step_3,2017-06-01 11:58:48
3,6019349,442094451_91531546617,154620534_35331068705_522317,step_2,2017-06-01 11:58:08
4,6019349,442094451_91531546617,154620534_35331068705_522317,step_1,2017-06-01 11:57:58

# merged df - df_final_web_data

In [5]:
df_final_web_data = pd.concat([df3, df4], axis = 0, join="outer")
display(df_final_web_data.shape)
df_final_web_data.info()
df_final_web_data.head(40)

(755405, 5)

<class 'pandas.core.frame.DataFrame'>
Index: 755405 entries, 0 to 412263
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     755405 non-null  int64
 1   visitor_id    755405 non-null  object
 2   visit_id      755405 non-null  object
 3   process_step  755405 non-null  object
 4   date_time     755405 non-null  object
dtypes: int64(1), object(4)
memory usage: 34.6+ MB

,client_id,visitor_id,visit_id,process_step,date_time
0,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:27:07
1,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:26:51
2,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:19:22
3,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:19:13
4,9988021,580560515_7732621733,781255054_21935453173_531117,step_3,2017-04-17 15:18:04
5,9988021,580560515_7732621733,781255054_21935453173_531117,step_2,2017-04-17 15:17:15
6,9988021,580560515_7732621733,781255054_21935453173_531117,step_1,2017-04-17 15:17:01
7,9988021,580560515_7732621733,781255054_21935453173_531117,start,2017-04-17 15:16:22
8,8320017,39393514_33118319366,960651974_70596002104_312201,confirm,2017-04-05 13:10:05
9,8320017,39393514_33118319366,960651974_70596002104_312201,step_3,2017-04-05 13:09:43
10,8320017,39393514_33118319366,960651974_70596002104_312201,step_2,2017-04-05 13:08:40
11,8320017,39393514_33118319366,960651974_70596002104_312201,step_1,2017-04-05 13:08:24
12,8320017,39393514_33118319366,960651974_70596002104_312201,start,2017-04-05 13:08:06
13,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:03
14,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:29:01
15,4033851,762728880_76361333336,949661017_22392791362_127391,confirm,2017-04-05 12:28:52
16,4033851,762728880_76361333336,949661017_22392791362_127391,step_3,2017-04-05 12:26:08
17,4033851,762728880_76361333336,949661017_22392791362_127391,step_2,2017-04-05 12:24:43
18,4033851,762728880_76361333336,949661017_22392791362_127391,step_1,2017-04-05 12:24:12
19,4033851,762728880_76361333336,949661017_22392791362_127391,start,2017-04-05 12:24:04
20,4033851,762728880_76361333336,949661017_22392791362_127391,step_2,2017-04-05 12:10:26
21,4033851,762728880_76361333336,949661017_22392791362_127391,step_3,2017-04-05 12:10:26
22,4033851,762728880_76361333336,949661017_22392791362_127391,step_2,2017-04-05 12:10:25
23,4033851,762728880_76361333336,949661017_22392791362_127391,step_3,2017-04-05 12:10:25
24,1982004,618934751_10082078917,132494692_73738638511_70823,confirm,2017-04-17 12:02:42
25,1982004,618934751_10082078917,132494692_73738638511_70823,step_3,2017-04-17 12:01:09
26,1982004,618934751_10082078917,132494692_73738638511_70823,step_2,2017-04-17 12:00:01
27,1982004,618934751_10082078917,132494692_73738638511_70823,step_1,2017-04-17 11:59:46
28,1982004,618934751_10082078917,132494692_73738638511_70823,start,2017-04-17 11:59:42
29,9294070,489274391_63794562906,116640698_27328181095_188045,start,2017-04-17 11:16:28
30,9294070,489274391_63794562906,116640698_27328181095_188045,start,2017-04-17 11:16:13
31,9466803,97277031_5793723360,812185460_4263902139_352107,start,2017-04-16 13:24:45
32,9466803,97277031_5793723360,812185460_4263902139_352107,step_2,2017-04-16 13:24:16
33,9466803,97277031_5793723360,812185460_4263902139_352107,step_1,2017-04-16 13:24:07
34,9466803,97277031_5793723360,812185460_4263902139_352107,start,2017-04-16 13:24:05
35,9466803,97277031_5793723360,812185460_4263902139_352107,step_1,2017-04-16 13:21:58
36,9466803,97277031_5793723360,812185460_4263902139_352107,start,2017-04-16 13:21:51
37,3170143,837774974_91015515080,758001412_25057963943_219559,confirm,2017-04-04 18:41:44
38,3170143,837774974_91015515080,758001412_25057963943_219559,step_3,2017-04-04 18:41:03
39,3170143,837774974_91015515080,758001412_25057963943_219559,step_2,2017-04-04 18:38:22

In [7]:
df_final_web_data.nunique()

client_id       120157
visitor_id      130236
visit_id        158095
process_step         5
date_time       629363
dtype: int64

In [8]:
duplicated = df_final_web_data.apply(lambda col: col.duplicated().sum())

duplicated_ = duplicated.to_frame(name="duplicated")

display(duplicated_)

              duplicated
client_id         635248
visitor_id        625169
visit_id          597310
process_step      755400
date_time         126042

In [9]:
df_final_web_data[df_final_web_data.isna().any(axis=1)]

Empty DataFrame
Columns: [client_id, visitor_id, visit_id, process_step, date_time]
Index: []

same step two times in a row with the same visit ID

same except time 
also the same for the start
we should keep the latest
for confirm we need to keep the first
everything has to match but the time (date should be the same)

## removing same steps duplicated

In [10]:
df_sorted = df_final_web_data.sort_values(by=["visit_id", "date_time"], ascending=True)

same_step_as_prev = (df_sorted["process_step"] == df_sorted["process_step"].shift(1)) & (df_sorted["visit_id"] == df_sorted["visit_id"].shift(1))
same_step_as_next = (df_sorted["process_step"] == df_sorted["process_step"].shift(-1)) & (df_sorted["visit_id"] == df_sorted["visit_id"].shift(-1))

drop_confirm = (df_sorted["process_step"] == "confirm") & same_step_as_prev

drop_start = (df_sorted["process_step"] == "start") & same_step_as_next

drop_steps = df_sorted["process_step"].isin(["step_1", "step_2", "step_3", "step_4"]) & same_step_as_prev


drop_start = (df_sorted["process_step"] == "start") & same_step_as_next
drop_steps = df_sorted["process_step"].isin(["step_1", "step_2", "step_3", "step_4"]) & same_step_as_prev

rows_to_delete = drop_confirm | drop_start | drop_steps

df_clean = df_sorted[~rows_to_delete]

df_final = df_clean.sort_values(by=["visit_id", "date_time"], ascending=[True, False]).reset_index(drop=True)

display(df_final.shape)
df_final.info()
df_final.head(40)
display(df_final)

(667425, 5)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 667425 entries, 0 to 667424
Data columns (total 5 columns):
 #   Column        Non-Null Count   Dtype
---  ------        --------------   -----
 0   client_id     667425 non-null  int64
 1   visitor_id    667425 non-null  object
 2   visit_id      667425 non-null  object
 3   process_step  667425 non-null  object
 4   date_time     667425 non-null  object
dtypes: int64(1), object(4)
memory usage: 25.5+ MB

,client_id,visitor_id,visit_id,process_step,date_time
0,3561384,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17
1,9056452,306992881_89423906595,1000165_4190026492_760066,confirm,2017-06-04 01:09:50
2,9056452,306992881_89423906595,1000165_4190026492_760066,step_3,2017-06-04 01:09:13
3,9056452,306992881_89423906595,1000165_4190026492_760066,step_2,2017-06-04 01:07:56
4,9056452,306992881_89423906595,1000165_4190026492_760066,step_1,2017-06-04 01:07:32
...,...,...,...,...,...
667420,7149380,483112224_46340533900,999992932_41666455053_671149,confirm,2017-06-06 16:04:08
667421,7149380,483112224_46340533900,999992932_41666455053_671149,step_3,2017-06-06 16:01:46
667422,7149380,483112224_46340533900,999992932_41666455053_671149,step_2,2017-06-06 15:47:32
667423,7149380,483112224_46340533900,999992932_41666455053_671149,step_1,2017-06-06 15:46:24
667424,7149380,483112224_46340533900,999992932_41666455053_671149,start,2017-06-06 15:46:03

In [11]:
df_final["date_time"] = pd.to_datetime(df_final["date_time"])
df_final.dtypes

client_id                int64
visitor_id              object
visit_id                object
process_step            object
date_time       datetime64[ns]
dtype: object

## Only confirmed

In [12]:
df_confirm = df_final[df_final["process_step"] == "confirm"]

display(df_confirm.info)

df_confirm.head(20)

<bound method DataFrame.info of         client_id             visitor_id                      visit_id  \
0         3561384   451664975_1722933822  100012776_37918976071_457913
1         9056452  306992881_89423906595     1000165_4190026492_760066
6         7338123  612065484_94198474375   100019538_17884295066_43909
15        2478628  754122351_18568832435  100022086_87870757897_149620
21        5303781  817384618_23455993918  100034012_10293842356_627828
...           ...                    ...                           ...
667396    4449968  842902495_57580498240  999976049_95772503197_182554
667401     829911  648229874_89449279372  999984454_18731538378_781808
667406    4064969  110735946_42614968419  999985675_64610694964_443659
667411    8374531  339629093_15796635997  999986292_55082159911_561557
667420    7149380  483112224_46340533900  999992932_41666455053_671149

       process_step           date_time
0           confirm 2017-04-26 13:22:17
1           confirm 2017-06-04 01:09:50
6           confirm 2017-04-09 16:24:58
15          confirm 2017-05-23 20:47:01
21          confirm 2017-06-06 14:08:29
...             ...                 ...
667396      confirm 2017-04-04 13:02:18
667401      confirm 2017-03-29 11:21:07
667406      confirm 2017-04-20 10:02:48
667411      confirm 2017-04-25 18:31:17
667420      confirm 2017-06-06 16:04:08

[90697 rows x 5 columns]>

,client_id,visitor_id,visit_id,process_step,date_time
0,3561384,451664975_1722933822,100012776_37918976071_457913,confirm,2017-04-26 13:22:17
1,9056452,306992881_89423906595,1000165_4190026492_760066,confirm,2017-06-04 01:09:50
6,7338123,612065484_94198474375,100019538_17884295066_43909,confirm,2017-04-09 16:24:58
15,2478628,754122351_18568832435,100022086_87870757897_149620,confirm,2017-05-23 20:47:01
21,5303781,817384618_23455993918,100034012_10293842356_627828,confirm,2017-06-06 14:08:29
40,2848373,66514700_31923440179,100065579_58979991824_496649,confirm,2017-04-15 14:33:28
45,3479519,194422203_56127484794,10006594_66157970412_679648,confirm,2017-04-13 11:56:12
52,8413245,61752232_53515470198,100075378_35009209505_135399,confirm,2017-06-03 20:15:31
59,5477656,164180384_39691984082,10007589_47780784567_391490,confirm,2017-05-18 08:03:33
66,529153,358679109_67662330057,100100247_25668133240_318122,confirm,2017-06-03 16:21:40
72,4456733,601916093_64335207773,100120278_95743019653_642729,confirm,2017-04-03 19:25:07
87,5108717,70145913_44783341760,100154767_60541320490_163313,confirm,2017-03-29 13:41:44
97,3061556,54742340_10443362363,100165170_70624318404_468222,confirm,2017-06-12 14:27:51
107,1409869,142747524_90273662602,100173185_24313831195_350873,confirm,2017-06-14 11:24:22
112,8631696,429350107_31978453627,100173292_91322748906_143563,confirm,2017-04-25 10:30:30
117,6789374,19782210_86170212999,100175041_74207131497_750935,confirm,2017-05-25 03:16:20
133,2029202,369331440_97107742514,100215152_57349471249_380824,confirm,2017-04-02 22:06:13
140,9341024,750259984_64435904859,100217156_67053490690_383412,confirm,2017-04-12 12:08:09
154,1848434,796394319_81197044162,10024342_90161571674_624251,confirm,2017-06-18 11:48:29
170,984526,101850349_35918274798,100254180_47139859079_984581,confirm,2017-04-05 21:47:43

## pivot to see nan

In [13]:
df_pivot = df_final.pivot_table(
    index=["visitor_id", "visit_id"],
    columns="process_step",
    values="date_time" ,
    aggfunc="min")

steps = ["start", "step_1", "step_2", "step_3", "confirm"]

df_pivot = df_pivot.reindex(columns=steps)

df_final_pivot = df_pivot.reset_index()

display(df_final_pivot)

process_step,visitor_id,visit_id,start,step_1,step_2,step_3,confirm
0,100011869_84756704576,406596333_52561114200_989487,2017-06-05 02:47:42,2017-06-05 02:47:47,2017-06-05 02:48:03,2017-06-05 02:50:18,NaT
1,100019786_4272121951,703380671_89376183829_330646,2017-04-15 15:13:33,2017-04-15 15:13:46,2017-04-15 15:14:21,2017-04-15 15:15:50,2017-04-15 15:16:18
2,100026388_52569174348,560716384_55516231568_734638,2017-06-09 18:37:59,2017-06-09 18:38:06,2017-06-09 18:40:07,2017-06-09 18:40:54,2017-06-09 18:41:43
3,100048572_12752788846,203019186_55602356305_152193,2017-04-03 02:00:50,NaT,NaT,NaT,NaT
4,100052114_10880025650,185528244_27988993926_55336,NaT,2017-05-14 16:59:26,NaT,NaT,NaT
...,...,...,...,...,...,...,...
158090,999993887_42794242929,984713970_16296160997_920979,2017-05-15 12:53:27,NaT,NaT,NaT,NaT
158091,999995931_60089148022,404770421_68000209065_385549,2017-04-05 12:22:14,2017-04-05 12:22:22,2017-04-05 12:23:03,2017-04-05 12:24:50,2017-04-05 12:26:07
158092,999997533_50295491521,584953917_38889231276_551903,2017-04-12 08:10:01,2017-04-12 08:10:14,2017-04-12 08:10:41,2017-04-12 08:11:48,2017-04-12 08:13:08
158093,999997533_50295491521,826796236_36192047424_492842,NaT,NaT,NaT,NaT,2017-04-13 07:41:14
158094,999998529_89539814462,583327415_19513940564_488564,2017-04-12 11:48:38,2017-04-12 11:49:27,2017-04-12 11:50:31,2017-04-12 11:52:11,2017-04-12 12:04:47

## compleition rate

In [17]:
unique_visits = df_final_pivot["visit_id"].nunique()

total_confirms_pivot = df_final_pivot["confirm"].notnull().sum()

conversion_rate = (total_confirms_pivot / unique_visits) * 100

print(f"Total visits (Pivot): {unique_visits:,}")
print(f"Total confirms (Pivot): {total_confirms_pivot:,}")
print(f"confirmation rate: {conversion_rate:.2f}%")

Total visits (Pivot): 158,095
Total confirms (Pivot): 89,826
confirmation rate: 56.82%

-time between steps

go through the process multiples times

step 2 to 3 

ppl who completed

compleition rate first  - filter by confirm - take IDs